// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfH7W6Rrq159vobc1wnWODIG50L9S2dRs',
    appId: '1:109398497549:web:16a2a62c2751b1206ef844',
    messagingSenderId: '109398497549',
    projectId: 'equmaintain',
    authDomain: 'equmaintain.firebaseapp.com',
    storageBucket: 'equmaintain.appspot.com',
    measurementId: 'G-LRV0WRQ3WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3aEZRKSDXwFJesx41UElWGzRJRLEVvQ',
    appId: '1:109398497549:android:e97d0fa601ae88346ef844',
    messagingSenderId: '109398497549',
    projectId: 'equmaintain',
    storageBucket: 'equmaintain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7uyaHMJFwjq-YN1CQP__fLdeqJ1O11qA',
    appId: '1:109398497549:ios:d884630346b43fff6ef844',
    messagingSenderId: '109398497549',
    projectId: 'equmaintain',
    storageBucket: 'equmaintain.appspot.com',
    iosBundleId: 'com.example.equmaintain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7uyaHMJFwjq-YN1CQP__fLdeqJ1O11qA',
    appId: '1:109398497549:ios:3f9f700154055bc76ef844',
    messagingSenderId: '109398497549',
    projectId: 'equmaintain',
    storageBucket: 'equmaintain.appspot.com',
    iosBundleId: 'com.example.equmaintain.RunnerTests',
  );
}
